#include "main.h"
#include "stm32f1xx_hal.h"
#include "cmsis_os.h"

#include <stdlib.h>
#include <string.h>

extern osThreadId nRF905HandlerHandle;
extern osTimerId nCarStatusHandle;
extern SPI_HandleTypeDef hspi1;
extern osMutexId nRF905OccupyHandle;

#define NRF905_SPI_CHN					hspi1
#define NRF905_POWER					3

#define NRF905_TX_ADDR_LEN				4
#define NRF905_RX_ADDR_LEN				4
#define NRF905_RX_PAYLOAD_LEN			32
#define NRF905_TX_PAYLOAD_LEN			NRF905_RX_PAYLOAD_LEN

/* Here is how the RF works:
 * UP keeps monitoring if there is any valid frame available (CD, AM, DR should be all SET) on certain channel for 300ms.
 * If yes, receive frame and continuously monitoring on this channel. If no, hop to next channel according to the hopping table.
 *
 * Down keeps transmitting frames every 100ms. If transmitting failed, (can not get valid response) down start hopping procedure.
 * Hopping procedure is to trying burst transmitting ACK frame continuously.
 * If transmitting failed, jump to next channel according to table and start to transmit again.
 * The TX&RX address is generated by some algorithm and is set at start up or during hopping
 *
 */
#define NRF905_RX_ADDRESS_IN_CR					5
#define NRF905_CMD_WC_MASK						0x0F
#define NRF905_CMD_WC(unWR_CFG_ByteIndex)		((unWR_CFG_ByteIndex) & NRF905_CMD_WC_MASK)	// Write Configuration register
#define NRF905_CMD_RC_MASK						0x0F
#define NRF905_CMD_RC(unRD_CFG_ByteIndex)		(((unRD_CFG_ByteIndex) & NRF905_CMD_RC_MASK) | 0x10)	// Read Configuration register
#define NRF905_CMD_WTP							0x20
#define NRF905_CMD_RTP							0x21
#define NRF905_CMD_WTA							0x22
#define NRF905_CMD_RTA							0x23
#define NRF905_CMD_RRP							0x24
#define NRF905_CMD_CC(unPwrChn)					((unPwrChn) | 0x1000)
#define CH_MSK_IN_CC_REG						0x01FF
#define NRF905_DR_IN_STATUS_REG(status)			((status) & (0x01 << 5))

typedef enum _nRF905Modes {
	NRF905_MODE_PWR_DOWN = 0,
	NRF905_MODE_STD_BY,
	NRF905_MODE_BURST_RX,
	NRF905_MODE_BURST_TX,
	NRF905_MODE_MAX
} nRF905Mode_t;

typedef struct _nRF905PinLevelInMode {
	int32_t nPWR_UP_PIN;
	int32_t nTRX_CE_PIN;
	int32_t nTX_EN_PIN;
} nRF905PinLevelInMode_t;

// Pin status according to each nRF905 mode
static const nRF905PinLevelInMode_t unNRF905MODE_PIN_LEVEL[] = {
		{ GPIO_PIN_RESET, GPIO_PIN_RESET, GPIO_PIN_RESET},
		{ GPIO_PIN_SET, GPIO_PIN_RESET, GPIO_PIN_RESET },
		{ GPIO_PIN_SET, GPIO_PIN_SET, GPIO_PIN_RESET },
		{ GPIO_PIN_SET, GPIO_PIN_SET, GPIO_PIN_SET } };

typedef struct _nRF905Status {
	uint32_t unNRF905RecvFrameCNT;
	uint32_t unNRF905SendFrameCNT;
	uint32_t unNRF905HoppingCNT;
	uint32_t unNRF905TxAddr;
	uint32_t unNRF905RxAddr;
	uint16_t unNRF905CHN_PWR;
	nRF905Mode_t tNRF905CurrentMode;
}nRF905Status_t;

static nRF905Status_t tNRF905Status = {0, 0, 0, 0, 0, NRF905_MODE_PWR_DOWN};

// MSB of CH_NO will always be 0
static const unsigned char NRF905_CR_DEFAULT[] = { 0x4C, 0x0C, // F=(422.4+(0x6C<<1)/10)*1; No retransmission; +6db; NOT reduce receive power
		(NRF905_RX_ADDR_LEN << 4) | NRF905_TX_ADDR_LEN,	// 4 bytes RX & TX address;
		NRF905_RX_PAYLOAD_LEN, NRF905_TX_PAYLOAD_LEN, // 16 bytes RX & TX package length;
		0x00, 0x0C, 0x40, 0x08,	// RX address is the calculation result of CH_NO
		0x58 };	// 16MHz crystal; enable CRC; CRC16

static int32_t nRF905PipeFd[2];
static uint16_t* pRoamingTable;
static int32_t nRoamingTableLen;

static int32_t setNRF905Mode(nRF905Mode_t tNRF905Mode) {
	if (tNRF905Mode >= NRF905_MODE_MAX){
		//NRF905_LOG_ERR("nRF905 Mode error.");
		return (-1);
	}
	if (tNRF905Mode == tNRF905Status.tNRF905CurrentMode){
		//NRF905_LOG_INFO("nRF905 Mode not changed, no need to set pin.");
		return 0;
	}

	HAL_GPIO_WritePin(NRF905_TX_EN_GPIO_Port, NRF905_TX_EN_Pin, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nTX_EN_PIN);
	HAL_GPIO_WritePin(NRF905_TRX_CE_GPIO_Port, NRF905_TRX_CE_Pin, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nTRX_CE_PIN);
	HAL_GPIO_WritePin(NRF905_PWR_UP_GPIO_Port, NRF905_PWR_UP_Pin, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nPWR_UP_PIN);
	tNRF905Status.tNRF905CurrentMode = tNRF905Mode;

	return 0;
}

void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi) {
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	vTaskNotifyGiveFromISR(nRF905HandlerHandle, &xHigherPriorityTaskWoken);
	portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}

static int32_t nRF905SPIDataRW(SPI_HandleTypeDef* pSPI_Handler, uint8_t* pBuff, uint8_t unBuffLen) {
	uint8_t* pRxBuff = NULL;
	uint32_t ulNotificationValue;
	const TickType_t xMaxBlockTime = pdMS_TO_TICKS(200);
	
	pRxBuff = malloc(unBuffLen);
	if (NULL == pRxBuff) {
		return (-1);
	}
	if (HAL_OK == HAL_SPI_TransmitReceive_DMA(pSPI_Handler, pBuff, pRxBuff, unBuffLen)) {
		ulNotificationValue = ulTaskNotifyTake( pdTRUE, xMaxBlockTime );
		if( ulNotificationValue == 1 ) {
			/* The transmission ended as expected. */
			memcpy(pBuff, pRxBuff, unBuffLen);
			free(pRxBuff);
			return 0;
		} else {
			/* The call to ulTaskNotifyTake() timed out. */
			free(pRxBuff);
			return (-1);
		}
	} else {
		return (-1);
	}
}

// No set mode in low level APIs because if you set Standby mode
// then after write SPI you don't know what to change back
static int32_t nRF905SPI_WR_CMD(unsigned char unCMD, const unsigned char *pData, int32_t nDataLen) {
	int32_t nResult;
	nRF905Mode_t tPreMode;
	unsigned char* pBuff;
	if (nDataLen > 0) {
		pBuff = malloc(nDataLen + 1);
		if (pBuff) {
			pBuff[0] = unCMD;
			memcpy(pBuff + 1, pData, nDataLen);
			tPreMode = tNRF905Status.tNRF905CurrentMode;
			setNRF905Mode(NRF905_MODE_STD_BY);
			nResult = nRF905SPIDataRW(&NRF905_SPI_CHN, pBuff, nDataLen + 1);
			setNRF905Mode(tPreMode);
			free(pBuff);
			return nResult;
		} else {
			return (-1);
		}
	} else {
		return (-1);
	}
}

static int32_t readStatusReg(void) {
	int32_t nResult;
	nRF905Mode_t tPreMode;
	unsigned char unStatus;
	unStatus = NRF905_CMD_RC(1);
	tPreMode = tNRF905Status.tNRF905CurrentMode;
	setNRF905Mode(NRF905_MODE_STD_BY);
	nResult = nRF905SPIDataRW(&NRF905_SPI_CHN, &unStatus, 1);
	setNRF905Mode(tPreMode);
	if (0 == nResult) {
		return unStatus;
	} else {
		return (-1);
	}
}

static int32_t readRxPayload(unsigned char* pBuff, int32_t nBuffLen) {
	int32_t nResult;
	unsigned char unReadBuff[33];
	nRF905Mode_t tPreMode;
	if ((nBuffLen > 0) && (nBuffLen < sizeof(unReadBuff))) {
		unReadBuff[0] = NRF905_CMD_RTP;
		tPreMode = tNRF905Status.tNRF905CurrentMode;
		setNRF905Mode(NRF905_MODE_STD_BY);
		nResult = nRF905SPIDataRW(&NRF905_SPI_CHN, unReadBuff, nBuffLen + 1);
		setNRF905Mode(tPreMode);
		memcpy(pBuff, unReadBuff + 1, nBuffLen);
		return nResult;
	} else {
		return (-1);
	}
}

int32_t readConfig(unsigned char unConfigAddr, unsigned char* pBuff, int32_t nBuffLen) {
	int32_t nResult;
	nRF905Mode_t tPreMode;
	unsigned char unReadBuff[33];
	if ((nBuffLen > 0) && (nBuffLen < sizeof(unReadBuff))) {
		unReadBuff[0] = NRF905_CMD_RC(unConfigAddr);
		tPreMode = tNRF905Status.tNRF905CurrentMode;
		setNRF905Mode(NRF905_MODE_STD_BY);
		nResult = nRF905SPIDataRW(&NRF905_SPI_CHN, unReadBuff, nBuffLen + 1);
		setNRF905Mode(tPreMode);
		memcpy(pBuff, unReadBuff + 1, nBuffLen);
		return nResult;
	} else {
		return (-1);
	}
}

static int32_t writeConfig(unsigned char unConfigAddr, const unsigned char* pBuff, int32_t nBuffLen) {
	return nRF905SPI_WR_CMD(NRF905_CMD_WC(unConfigAddr), pBuff, nBuffLen);
}

static int32_t writeTxAddr(uint32_t unTxAddr) {
	return nRF905SPI_WR_CMD(NRF905_CMD_WTA, (unsigned char*)(&unTxAddr), 4);
}

static int32_t writeRxAddr(uint32_t unRxAddr) {
	return writeConfig(NRF905_RX_ADDRESS_IN_CR, (unsigned char*)(&unRxAddr), 4);
}

// TX and RX address are already configured during hopping
static int32_t writeTxPayload(unsigned char* pBuff, int32_t nBuffLen) {
	return writeConfig(NRF905_CMD_WTP, pBuff, nBuffLen);
}

static int32_t writeFastConfig(uint16_t unPA_PLL_CHN) {
	int32_t nResult;
	nRF905Mode_t tPreMode;
	tPreMode = tNRF905Status.tNRF905CurrentMode;
	setNRF905Mode(NRF905_MODE_STD_BY);
	nResult = nRF905SPIDataRW(&NRF905_SPI_CHN, (unsigned char *)(&unPA_PLL_CHN), 2);
	setNRF905Mode(tPreMode);
	return nResult;
}

static void readDataFromNRF905(void) {
	static unsigned char unReadBuff[32];
	static int32_t nStatusReg;

	setNRF905Mode(NRF905_MODE_STD_BY);
	// make sure DR was set
	nStatusReg = readStatusReg();
	if ((nStatusReg >= 0) && (NRF905_DR_IN_STATUS_REG(nStatusReg) == 0)) {
		// Strange happens, do something?
	} else {
		// reset monitor timer since communication seems OK
		tNRF905Status.unNRF905RecvFrameCNT++;
		readRxPayload(unReadBuff, sizeof(unReadBuff));
	}
	setNRF905Mode(NRF905_MODE_BURST_RX);
}

int32_t nRF905DataReadyHandler(void) {
	if (NRF905_MODE_BURST_RX == tNRF905Status.tNRF905CurrentMode) {
		readDataFromNRF905();
		return 0;
	} else if (NRF905_MODE_BURST_TX == tNRF905Status.tNRF905CurrentMode) {
		setNRF905Mode(NRF905_MODE_BURST_RX);
		return 0;		
	} else {
		return (-1);
	}
}

static int32_t nRF905CRInitial(void) {
	return writeConfig(0, NRF905_CR_DEFAULT, sizeof(NRF905_CR_DEFAULT));
}

static uint32_t getTxAddrFromChnPwr(uint32_t unNRF905CHN_PWR) {
	return ((unNRF905CHN_PWR | (unNRF905CHN_PWR << 16)) & 0xA33D59AA);
}

static uint32_t getRxAddrFromChnPwr(uint16_t unNRF905CHN_PWR) {
	return ((unNRF905CHN_PWR | (unNRF905CHN_PWR << 16)) & 0x5CA259AA);
}

#define GET_CHN_PWR_FAST_CONFIG(x, y) 		((x) | ((y) << 10))

static void roamNRF905(void) {
	static int32_t nHoppingPoint = 0;

	setNRF905Mode(NRF905_MODE_STD_BY);
	tNRF905Status.unNRF905CHN_PWR = GET_CHN_PWR_FAST_CONFIG(pRoamingTable[nHoppingPoint], NRF905_POWER);
	(nHoppingPoint < (nRoamingTableLen - 1)) ? (nHoppingPoint++):(nHoppingPoint = 0);
	tNRF905Status.unNRF905HoppingCNT++;
	tNRF905Status.unNRF905TxAddr = getTxAddrFromChnPwr(tNRF905Status.unNRF905CHN_PWR);
	tNRF905Status.unNRF905RxAddr = getRxAddrFromChnPwr(tNRF905Status.unNRF905CHN_PWR);
	writeFastConfig(tNRF905Status.unNRF905CHN_PWR);
	writeTxAddr(tNRF905Status.unNRF905TxAddr);
	writeRxAddr(tNRF905Status.unNRF905RxAddr);
	setNRF905Mode(NRF905_MODE_BURST_RX);
}

int32_t nRF905Initial(void) {
	setNRF905Mode(NRF905_MODE_STD_BY);
	vTaskDelay(pdMS_TO_TICKS(3));
	nRF905CRInitial();

	return 0;
}

int32_t nRF905SendFrame(unsigned char* pReadBuff, int32_t nBuffLen) {
	setNRF905Mode(NRF905_MODE_STD_BY);
	writeTxPayload(pReadBuff, nBuffLen);
	setNRF905Mode(NRF905_MODE_BURST_TX);
	tNRF905Status.unNRF905SendFrameCNT++;
	return 0;
}

uint32_t getNRF905StatusRecvFrameCNT(void) {
	uint32_t unNRF905RecvFrameCNT;
	osMutexWait(nRF905OccupyHandle, 0);
	unNRF905RecvFrameCNT = tNRF905Status.unNRF905RecvFrameCNT;
	osMutexRelease(nRF905OccupyHandle);
	return unNRF905RecvFrameCNT;
}

uint32_t getNRF905StatusSendFrameCNT(void) {
	uint32_t unNRF905SendFrameCNT;
	osMutexWait(nRF905OccupyHandle, 0);
	unNRF905SendFrameCNT = tNRF905Status.unNRF905SendFrameCNT;
	osMutexRelease(nRF905OccupyHandle);
	return unNRF905SendFrameCNT;
}

uint32_t getNRF905StatusHoppingCNT(void) {
	uint32_t unNRF905HoppingCNT;
	osMutexWait(nRF905OccupyHandle, 0);
	unNRF905HoppingCNT = tNRF905Status.unNRF905HoppingCNT;
	osMutexRelease(nRF905OccupyHandle);
	return unNRF905HoppingCNT;
}

void queryCarStatus(void const * argument) {
	
}

void startNRF905Trans(void const * argument) {
	nRF905Initial();
	osTimerStart(nCarStatusHandle, 200);
	while (1) {
		vTaskDelay(pdMS_TO_TICKS(5000));
	}
}
